# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

# cassandra values
cassandra:
  config:
    cluster_size: 1
    seed_size: 1
resources:
  enabled: false

config:
  managedByConfigPod:
    enabled: true
    # syncUrl: http://sdcore-adapter-v3.aether-roc.svc:8080/synchronize
  config4g:
    deploy: true
  hss:
    bootstrap:
      users: []
      staticusers: []
  spgwc:
    pfcp: true
    cfgFiles:
      cp.json:
        ip_pool_config:
          ueIpPool:
            ip: "172.250.0.0"
            mask: "255.255.0.0"
          staticUeIpPool:
            ip: "172.250.1.0"
            mask: "255.255.255.0"
  simapp:
    cfgFiles:
      simapp.yaml:
        configuration:
          provision-network-slice: true
          sub-provision-endpt:
            addr: config4g
            port: 5000
          subscribers:
          - ueId-start: 208014567891201
            ueId-end: 208014567891211
            plmnId: 20801
            opc: "d4416644f6154936193433dd20a0ace0"
            op: ""
            key: "465b5ce8b199b49faa5f0a2ee238a6bc"
            sequenceNumber: 96
          device-groups:
          - name:  "4g-oaisim-user"
            imsis:
              - "208014567891201"
              - "208014567891202"
            ip-domain-name: "pool1"
            ip-domain-expanded:
              dnn: internet
              dns-primary: "8.8.8.8"
              mtu: 1460
              ue-ip-pool: "172.250.0.0/16"
            site-info: "aiab"
          network-slices:
          - name: "default"
            slice-id:
              sd: "010203"
              sst: 1
            site-device-group:
            - "4g-oaisim-user"
            applications-information:
            - app-name: "default-app"
              end-port: 40000
              endpoint: "1.1.1.1/32"
              protocol: 17
              start-port: 40000
            deny-applications:
            - "iot-app-deny"
            permit-applications:
            - "iot-app1-permit"
            - "iot-app2-permit"
            qos:
              downlink: 20
              traffic-class: "platinum"
              uplink: 40
            site-info:
              gNodeBs:
              - name: "aiab-gnb1"
                tac: 1
              plmn:
                mcc: "208"
                mnc: "01"
              site-name: "aiab"
              upf:
                upf-name: "upf"
                upf-port: 8805
