# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0
mongodb:
  usePassword: false
  persistence:
    enabled: false
resources:
  enabled: false

config:
  managedByConfigPod:
    enabled: true
    # syncUrl: http://sdcore-adapter-v4.aether-roc.svc:8080/synchronize
  smf:
    cfgFiles:
      # https://github.com/free5gc/free5gc/blob/main/config/pcfcfg.yaml
      smfcfg.conf:
        configuration:
          mongodb:       # the mongodb connected by this PCF
            name: smf # name of the mongodb
            url: mongodb://mongodb:27017
  pcf:
    cfgFiles:
      # https://github.com/free5gc/free5gc/blob/main/config/pcfcfg.yaml
      pcfcfg.conf:
        info:
          version: 1.0.0
          description: PCF initial local configuration
        configuration:
          mongodb:       # the mongodb connected by this PCF
            name: free5gc                  # name of the mongodb
            url: mongodb://mongodb:27017
  nrf:
    cfgFiles:
      # https://github.com/free5gc/free5gc/blob/main/config/nrfcfg.yaml
      nrfcfg.conf:
        configuration:
          MongoDBName: free5gc # database name in MongoDB
          MongoDBUrl: mongodb://mongodb:27017
          #MongoDBUrl: mongodb://mongodb:27017 #works with db in omec name space
  simapp:
    cfgFiles:
      simapp.yaml:
        configuration:
          MongoDBName: free5gc # database name in MongoDB
          MongoDBUrl: mongodb://mongodb:27017
          provision-network-slice: true
          sub-provision-endpt:
            addr: webui
            port: 5000
          subscribers:
          - ueId-start: 208930100007487
            ueId-end: 208930100007501
            plmnId: 20893
            opc: "981d464c7c52eb6e5036234984ad0bcf"
            op: ""
            key: "5122250214c33e723a5dd523fc145fc0"
            sequenceNumber: "16f3b3f70fc2"
          device-groups:
          - name:  "5g-gnbsim-user"
            imsis:
              - "208930100007487"
              - "208930100007488"
              - "208930100007489"
              - "208930100007490"
              - "208930100007491"
              - "208930100007492"
              - "208930100007493"
              - "208930100007494"
              - "208930100007495"
              - "208930100007496"
              - "208930100007497"
              - "208930100007498"
              - "208930100007499"
              - "208930100007500"
              - "208930100007501"
            ip-domain-name: "pool1"
            ip-domain-expanded:
              dnn: internet
              dns-primary: "8.8.8.8"
              mtu: 1460
              ue-ip-pool: "172.250.0.0/16"
              ue-dnn-qos:
                dnn-mbr-downlink: 20000000
                dnn-mbr-uplink: 4000000
                bitrate-unit: bps
                traffic-class:  #default bearer QCI/ARP
                  name: "platinum"
                  qci: 9
                  arp: 6
                  pdb: 300
                  pelr: 6
            site-info: "aiab"
          network-slices:
          - name: "default"
            slice-id:
              sd: "010203"
              sst: 1
            site-device-group:
            - "5g-gnbsim-user"
            application-filtering-rules:
            - rule-name: "ALLOW-ALL"
              priority: 250
              action: "permit"
              endpoint: "0.0.0.0/0"
            site-info:
              gNodeBs:
              - name: "aiab-gnb1"
                tac: 1
              plmn:
                mcc: "208"
                mnc: "93"
              site-name: "aiab"
              upf:
                upf-name: "upf"
                upf-port: 8805
