# Copyright 2022-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

resources:
  - ./hss-monitor.yaml
  - ./mme-monitor.yaml
  - ./spgwc-monitor.yaml
  - ./upf-monitor.yaml

configmapGenerator:
  - name: grafana-ops-dashboards
    namespace: cattle-dashboards
    files:
      - ./aiab-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
